[package]
name = "overlay"
version = "0.1.0"
authors = ["qthree <qthree3@gmail.com>"]
edition = "2018"

[features]
default = ["backend-winit-gl"]
backend-winit-gl = ["imgui", "imgui-glium-renderer", "imgui-winit-support", "glium"]
backend-sdl2 = ["sdl2"]
static-link = ["backend-sdl2", "sdl2/static-link"]

[dependencies]
bridge = { path = "../../crates/bridge" }
protocol = { path = "../../crates/protocol" }
fo_defines = { path = "../../crates/fo_defines" }
achtung = { path = "../../crates/achtung" }

#orbtk = { path = "../orbtk" }
#orbclient = "0.3.22"
#sdl2 = { path = "../rust-sdl2", features = ["bundled", "use-bindgen"] }
sdl2 = { version = "0.32" , features = ["bundled", "use-bindgen", "unsafe_textures"], optional = true }
winapi = { version = "0.3", features = ["winuser"] }
crossbeam = "0.7"
reqwest = { version = "0.10", default-features = false, features = ["rustls-tls", "blocking"] }
image = { version = "0.22", default-features = false, features = ["png_codec"] }
imgui = { path = "../../../../rust/old_overlay/imgui-rs", default-features = false, features = ["glium"], optional = true }
imgui-glium-renderer = { path = "../../../../rust/old_overlay/imgui-rs/imgui-glium-renderer", optional = true }
imgui-winit-support = { path = "../../../../rust/old_overlay/imgui-rs/imgui-winit-support", optional = true }
#imgui = { git = "https://github.com/Gekkio/imgui-rs.git", default-features = false, features = ["glium"], optional = true }
#imgui-glium-renderer = { git = "https://github.com/Gekkio/imgui-rs.git", optional = true }
#imgui-winit-support = { git = "https://github.com/Gekkio/imgui-rs.git", optional = true }
glium = { version = "0.25", default-features = true, optional = true }
colorsys = "0.5"
clap = "2.33"
clipboard = "0.5"
#legion = {path = "D:/rust/legion", default-features = false }

[profile.release]
lto = "fat"
debug = 0
codegen-units = 1

[profile.dev]
lto = false
opt-level = 1
debug = 0

[patch.crates-io]
#glium  = { git = 'https://github.com/qthree/glium.git' }
glium  = { path = '../../../../rust/old_overlay/glium' }
