[package]
name = "overlay_launcher"
version = "0.1.0"
authors = ["qthree <qthree3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
achtung = {path = "../../crates/achtung"}

[profile.release]
lto = "fat"
debug = 0
codegen-units = 1

[profile.dev]
lto = false
opt-level = 0
debug = 2
