[package]
name = "map_fix_protos"
version = "0.1.0"
authors = ["qthree <qthree3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fo_map_format = { path = "../../crates/fo_map_format" }
fo_proto_format = { git = "https://github.com/fonline-roleplay/fo_proto_format.git" }
nom_prelude = { path = "../../crates/nom_prelude" }
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }

[profile.release]
lto = "fat"
debug = 0
codegen-units = 1

[profile.dev]
lto = false
opt-level = 0
debug = 2
